export class PassengerTickets {
    id:number;
    ticketnumber:string;
    personName:string;
    infantCount:string;
    personAge:string;
    email:string;
    seat:string;
    dateofjourney:string;
    mobileNumber:string;
    aadharNumber:string;
    flightnumber:string;
    flightname:string;
    flightorigin:string;
    flightdest:string;
    flighttime:string;
    food:string;
    childAllow:string;
    wheelChairProvision:string;
    address:string;
    gender:string;
    checkedin:boolean;
}
